### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 17

### ISSUE THREAD

**Issue by drgeb** [dekorateio/dekorate#309]
Execution failed for task ':compileJava'.
> java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 17

I am not sure what is causing this. Not sure also which files you want to see, let me know I can upload these. Thanks

below is part of the stacktrace

Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 17
        at io.dekorate.project.GradleInfoReader.lambda$readSettingsGradle$1(GradleInfoReader.java:119)
        at io.dekorate.project.GradleInfoReader.readSettingsGradle(GradleInfoReader.java:118)
        at io.dekorate.project.GradleInfoReader.getInfo(GradleInfoReader.java:77)
        at io.dekorate.project.FileProjectFactory.lambda$getProjectInfo$2(FileProjectFactory.java:83)
        at io.dekorate.project.FileProjectFactory.getProjectInfo(FileProjectFactory.java:83)
        at io.dekorate.project.FileProjectFactory.createInternal(FileProjectFactory.java:57)
        at io.dekorate.project.FileProjectFactory.create(FileProjectFactory.java:46)
        at io.dekorate.project.AptProjectFactory.createInternal(AptProjectFactory.java:50)
        at io.dekorate.project.AptProjectFactory.create(AptProjectFactory.java:40)
        at io.dekorate.processor.AbstractAnnotationProcessor.init(AbstractAnnotationProcessor.java:61)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
        at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.init(NonIncrementalProcessor.java:33)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$301(TimeTrackingProcessor.java:37)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$4.create(TimeTrackingProcessor.java:88)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$4.create(TimeTrackingProcessor.java:85)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.init(TimeTrackingProcessor.java:85)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:678)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:778)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:873)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1214)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1326)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        ... 117 more

**Comment by iocanel** [comment]
@drgeb: dekorate does the parsing of the files manually (without reusing gradle libs). Apparently, we have a bug there. I will have a look.

If you could share your gradle files, it would be great!

**Comment by iocanel** [comment]
@drgeb: This is now fixed on master.
