### ISSUE TITLE
container image build from the example wont start

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#451]
## Issue

The spring boot prometheus dekorate example - container image cannot be started by the pod. See error hereafter

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/dekorate/example/sbonkubernetes/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:45)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

## Steps to reproduce

```
git clone https://github.com/dekorateio/dekorate.git & cd dekorate/examples/spring-boot-with-prometheus-on-kubernetes-example
mvn clean install

docker build -t cmoulliard/spring-boot-prometheus .
docker push cmoulliard/spring-boot-prometheus

# Remark : find/replace the image within the deployment definition

kubectl apply -f dekorate/examples/spring-boot-with-prometheus-on-kubernetes-example/target/classes/META-INF/dekorate/kubernetes.yml
```

**Comment by cmoulliard** [comment]
We should perhaps within the doc mentions that currently the `dockerfile` still use JDK8 and then the compilation should be done against this JVM version. WDYT @iocanel

**Comment by iocanel** [comment]
Yeah, we could!
I am wondering though if we should also bump to JDK11. 

wdyt?

**Comment by cmoulliard** [comment]
> JDK11

We could but I'm horrified to read such a thread - https://stackoverflow.com/questions/53375613/why-is-the-java-11-base-docker-image-so-large-openjdk11-jre-slim. Which slim version should we then use ?

**Comment by cmoulliard** [comment]
We should perhaps use the UBI image when red hat will release it or this one : FROM registry.redhat.io/openjdk/openjdk-11-rhel8 maybe
