### ISSUE TITLE
GradleInfo reader assigns JAVA to groovy

### ISSUE THREAD

**Issue by pgressa** [dekorateio/dekorate#616]
Hi, 

I'm trying to use Dekorate in version 1.0.1 using gradle as build tool. The manifests are generated:
```
> Task :compileJava FAILED
[WARN] Could not detect project version. Using 'latest'.
[INFO] Found @KubernetesApplication on: example.micronaut.Application
[INFO] Initializing dekorate session.
[INFO] Generating manifests.
[INFO] Processing kubernetes configuration.
[INFO] Writing: file:/private/var/folders/_q/qs930dw93b173jy20p05b3x00000gn/T/dekorate6190129776997829285/build/classes/java/main/META-INF/dekorate/kubernetes.json
[INFO] Writing: file:/private/var/folders/_q/qs930dw93b173jy20p05b3x00000gn/T/dekorate6190129776997829285/build/classes/java/main/META-INF/dekorate/kubernetes.yml

```

However the build on 
```
Caused by: java.lang.RuntimeException: Error writing resources
        at io.dekorate.processor.SimpleFileWriter.write(SimpleFileWriter.java:89)
        at io.dekorate.processor.AptWriter.lambda$write$1(AptWriter.java:69)
        at io.dekorate.processor.AptWriter.write(AptWriter.java:69)
        at io.dekorate.Session.close(Session.java:207)
        at io.dekorate.kubernetes.apt.KubernetesAnnotationProcessor.process(KubernetesAnnotationProcessor.java:42)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.process(NonIncrementalProcessor.java:45)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$401(TimeTrackingProcessor.java:37)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:99)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:96)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.process(TimeTrackingProcessor.java:96)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:635)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1041)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1206)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 122 more
Caused by: java.io.FileNotFoundException: /private/var/folders/_q/qs930dw93b173jy20p05b3x00000gn/T/dekorate6190129776997829285/build/classes/groovy/main/../.dekorate/config/docker.yml (No such file or directory)
        at io.dekorate.processor.SimpleFileWriter.write(SimpleFileWriter.java:81)
        ... 142 more

```

Obviously Dekorate tries to operate with files on path `/build/classes/groovy/main`, interesting fact is that  the k8s manifests were generated into `/build/classes/java/main/`. 

Anyway, for version 1.0.0, it works. There are some commits in [1.0.0...1.0.1](https://github.com/dekorateio/dekorate/compare/1.0.0...1.0.1) that could introduce such regression.

**Comment by pgressa** [comment]
For a reproducer:
1. Change default here https://github.com/dekorateio/dekorate/blob/1.0.1/examples/spring-boot-with-gradle-on-kubernetes-example/build.gradle or use 1.0.1
1. run `./gradlew compileJava`

**Comment by iocanel** [comment]
@pgressa: Thanks for reporting!

Will have a look shortly.

**Comment by iocanel** [comment]
@pgressa: Also, note that most of us are not frequent gradle users, so your feedback is really important to us.

**Comment by lujun2** [comment]
Similar issue here, but this time is for [Kotlin](https://kotlinlang.org/)

Reproduce repo: https://github.com/lujun2/SampleKubernetesApplication

Maybe we should "recognize" the language

**Comment by iocanel** [comment]
> Similar issue here, but this time is for [Kotlin](https://kotlinlang.org/)
> 
> Reproduce repo: https://github.com/lujun2/SampleKubernetesApplication
> 
> Maybe we should "recognize" the language

I am wondering if checking the path is enough for this.

**Comment by lujun2** [comment]
> > Similar issue here, but this time is for [Kotlin](https://kotlinlang.org/)
> > Reproduce repo: https://github.com/lujun2/SampleKubernetesApplication
> > Maybe we should "recognize" the language
> 
> I am wondering if checking the path is enough for this.

It's not quite offen, but Java & Kotlin can be mixed in one project

https://kotlinlang.org/docs/tutorials/mixing-java-kotlin-intellij.html

**Comment by pgressa** [comment]
The question is, whether the manifests have to be generated into the language specific folder. At the end of the day, the manifest itself does not have anything common with language the service is written in, is that correct?

Furthermore, as @lujun2 mentioned,  one project can mix groovy, kotlin, java source code, so the only differentiator could be, what is the source code of main app / annotated classes.

**Comment by pgressa** [comment]
@iocanel is there gonna be 1.0.2 released with the fix soon? B/c I've added dekorate support into https://github.com/micronaut-projects/micronaut-starter/pull/446 and I'm basically waiting for the fix to finish the PR

**Comment by iocanel** [comment]
@pgressa: If you need it, then I'll release it. :-D

**Comment by iocanel** [comment]
> The question is, whether the manifests have to be generated into the language specific folder. At the end of the day, the manifest itself does not have anything common with language the service is written in, is that correct?
> 
> Furthermore, as @lujun2 mentioned, one project can mix groovy, kotlin, java source code, so the only differentiator could be, what is the source code of main app / annotated classes.

Don't remember exactly why we ended up using those folders. I think that initially we just used the Annotation Processor facilities, and went with their defaults (the default dir where the Filer created resources, or something like that). Later on we bypassed those, but kept their defaults.

Currently, I think that nothing forces us to these folders and maybe in 2.0.x we should simplify it and just go with build/dekorate or something like this.

**Comment by iocanel** [comment]
> @iocanel is there gonna be 1.0.2 released with the fix soon? B/c I've added dekorate support into [micronaut-projects/micronaut-starter#446](https://github.com/micronaut-projects/micronaut-starter/pull/446) and I'm basically waiting for the fix to finish the PR

Initially, we provided starters for micronaut and wanted to provide even better support for it. At some point it got accidentially wiped and no one complaint so here we are now. Let me know if you need anything to improve micronaut support.

**Comment by pgressa** [comment]
@iocanel yeah we noticed :). Currently this is just starter support to simply generate annotations, however we plan to extend the support so the annotations will be automatically populated by values from app context. Anyway, would you be please so kind and release 1.0.2 with the fix? Thanks!

**Comment by iocanel** [comment]
@pgressa: 1.0.2 is on central ;-)
