### ISSUE TITLE
Deployement error when group id is too big

### ISSUE THREAD

**Issue by aureamunoz** [dekorateio/dekorate#788]
I have this error when trying to deploy a Quarkus microservice in OpenShift in one single step, 
I run the `./mvnw clean package -Dquarkus.kubernetes.deploy=true` command and I get the following error:
```
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  53.599 s
[INFO] Finished at: 2021-09-17T13:14:16Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.2.2.Final:build (default) on project rest-hero: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftBuildFromJar threw an exception: java.lang.RuntimeException: Error creating the openshift binary build archive.
[ERROR]         at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:329)
[ERROR]         at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuildFromJar(OpenshiftProcessor.java:252)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.IllegalArgumentException: group id '1000690000' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit
[ERROR]         at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:651)
[ERROR]         at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumberWithPosixMessage(TarArchiveOutputStream.java:644)
[ERROR]         at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:626)
[ERROR]         at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:377)
[ERROR]         at io.dekorate.utils.Packaging.putTarEntry(Packaging.java:139)
[ERROR]         at io.dekorate.utils.Packaging$1.visitFile(Packaging.java:123)
[ERROR]         at io.dekorate.utils.Packaging$1.visitFile(Packaging.java:99)
[ERROR]         at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
[ERROR]         at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
[ERROR]         at io.dekorate.utils.Packaging.packageFile(Packaging.java:99)
[ERROR]         at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:324)
[ERROR]         ... 12 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

This comes from Dekorate from what I see when 
 ```
[user@workspace57dbnhjoas24i47a quarkus-workshop-super-heroes]$ id
uid=1000690000(user) gid=0(root) groups=0(root),1000690000(user)
```

I think I would add this line tarArchiveOutputStream.setLongFileMode(TarArchiveOutputStream.LONGFILE_POSIX); also in the putTarEntry method

**Comment by cmoulliard** [comment]
I created a test case to reproduce the error. It appears that to fix the problem we must also set the parameters
```
os.setLongFileMode(TarArchiveOutputStream.BIGNUMBER_POSIX);
os.setBigNumberMode(2);
```
as the code of of the class check if bigNumberMode is equal to BIGBUMBER_POSIX and thrown an examption id they are not equal: https://gist.github.com/cmoulliard/69ee6fda058f93a1ec296aaf3edbc983#file-tararchiveoutputstream-java-L374-L378

@aureamunoz @iocanel
