### ISSUE TITLE
Port forwarding is consistently failing in K8s tests (probably also in OCP tests)

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#818]
Tests like:

```java
try (LocalPortForward p = client.pods().withName(pod.getMetadata().getName()).portForward(8080)) {
      assertTrue(p.isAlive());
      URL url = new URL("http://localhost:"+p.getLocalPort()+"/");

      OkHttpClient client = new OkHttpClient();
      Request request = new Request.Builder().get().url(url).build();
      Response response = client.newCall(request).execute(); // line 1
      assertEquals(response.body().string(), "Hello world");
    }
```

This will fail at line 1 with the following stacktrace:

```
java.io.IOException: unexpected end of stream on Connection{localhost:45389, proxy=DIRECT hostAddress=localhost/0:0:0:0:0:0:0:1:45389 cipherSuite=none protocol=http/1.1}
	at io.dekorate.example.SpringBootOnKubernetesIT.shouldRespondWithHelloWorld(SpringBootOnKubernetesIT.java:64)
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at io.dekorate.example.SpringBootOnKubernetesIT.shouldRespondWithHelloWorld(SpringBootOnKubernetesIT.java:64)
```

Diagnosis information:

```
[INFO] Created: Service name:spring-boot-on-kubernetes-example.
[INFO] Created: Deployment name:spring-boot-on-kubernetes-example.
[INFO] Waiting until ready (300000 ms)...
[INFO] Waited: 21265 ms.
[INFO] Found version:1.20
Forwarding port from pod: spring-boot-on-kubernetes-example-644bf69f97-gnvr5
13:27:50.763 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
13:27:50.764 [main] DEBUG io.fabric8.kubernetes.client.Config - Found for Kubernetes config at: [/home/runner/.kube/config].
13:27:51.028 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onOpen
13:27:51.044 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onMessage(ByteString)
13:27:51.049 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onMessage(ByteString)
13:27:51.050 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onMessage(ByteString)
13:27:51.051 [OkHttp https://10.1.0.149:8443/...] ERROR io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - Received an error from the remote socket
13:27:51.060 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onClosing. Code=1000, Reason=
13:27:51.118 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onOpen
13:27:51.128 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onMessage(ByteString)
13:27:51.128 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onMessage(ByteString)
13:27:51.130 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onMessage(ByteString)
13:27:51.131 [OkHttp https://10.1.0.149:8443/...] ERROR io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - Received an error from the remote socket
13:27:51.135 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onClosing. Code=1000, Reason=
13:27:51.135 [OkHttp WebSocket https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onFailure
13:27:51.135 [OkHttp https://10.1.0.149:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocket - FWD: onClosed. Code=1000, Reason=
[INFO] Diagnostics for kind: [Deployment] with name : [spring-boot-on-kubernetes-example].
[INFO] ---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: spring-boot-on-kubernetes-example
    app.kubernetes.io/version: 2.6-SNAPSHOT
  name: spring-boot-on-kubernetes-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot-on-kubernetes-example
      app.kubernetes.io/version: 2.6-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
      labels:
        app.kubernetes.io/name: spring-boot-on-kubernetes-example
        app.kubernetes.io/version: 2.6-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: testme/spring-boot-on-kubernetes-example:2.6-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/info
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: spring-boot-on-kubernetes-example
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10

[INFO] 	---
[INFO] Deployment: spring-boot-on-kubernetes-example [1/1]
[INFO] 	Type                 Status     Message                                 
[INFO] 	Available            True       Deployment has minimum availability.    
[INFO] 	Progressing          True       ReplicaSet "spring-boot-on-kubernetes-example-644bf69f97" has successfully progressed.
[INFO] Events of Deployment: [spring-boot-on-kubernetes-example]
[INFO] 	---
[INFO] Diagnostics for kind: [Pod] with name : [spring-boot-on-kubernetes-example-644bf69f97-gnvr5].
[INFO] Container statuses of Pod:spring-boot-on-kubernetes-example-644bf69f97-gnvr5
[INFO] 	Name                                     Running Ready   Image
[INFO] 	spring-boot-on-kubernetes-example        true    true    testme/spring-boot-on-kubernetes-example:2.6-SNAPSHOT
[INFO] Events of Pod: [spring-boot-on-kubernetes-example-644bf69f97-gnvr5]
[INFO] Scheduled		Successfully assigned default/spring-boot-on-kubernetes-example-644bf69f97-gnvr5 to fv-az39-625
[INFO] Pulled		Container image "testme/spring-boot-on-kubernetes-example:2.6-SNAPSHOT" already present on machine
[INFO] Created		Created container spring-boot-on-kubernetes-example
[INFO] Started		Started container spring-boot-on-kubernetes-example
[INFO] 	---
[INFO] Logs of pod: [spring-boot-on-kubernetes-example-644bf69f97-gnvr5], container: [spring-boot-on-kubernetes-example]
[INFO] 
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)

2021-11-11 13:27:32.684  INFO 10 --- [           main] io.dekorate.example.Main                 : Starting Main using Java 11.0.13 on spring-boot-on-kubernetes-example-644bf69f97-gnvr5 with PID 10 (/spring-on-kubernetes-example.jar started by root in /)
2021-11-11 13:27:32.690  INFO 10 --- [           main] io.dekorate.example.Main                 : No active profile set, falling back to default profiles: default
2021-11-11 13:27:34.801  INFO 10 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9090 (http)
2021-11-11 13:27:34.816  INFO 10 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-11-11 13:27:34.816  INFO 10 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.45]
2021-11-11 13:27:34.959  INFO 10 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-11-11 13:27:34.959  INFO 10 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2159 ms
2021-11-11 13:27:35.934  INFO 10 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-11-11 13:27:36.257  INFO 10 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2021-11-11 13:27:36.306  INFO 10 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9090 (http) with context path ''
2021-11-11 13:27:36.322  INFO 10 --- [           main] io.dekorate.example.Main                 : Started Main in 4.61 seconds (JVM running for 5.748)
2021-11-11 13:27:49.857  INFO 10 --- [nio-9090-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-11-11 13:27:49.858  INFO 10 --- [nio-9090-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-11-11 13:27:49.860  INFO 10 --- [nio-9090-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
```

The same scenario works fine using Kind in local, so I guess it must be an environmental issue in CI.
Other things I tried:
- Increase liveness probe intial delay
- Upgrade kind and minishift
- Not install service operators (just to have the same environment I have in my local where is working)
- Use Java 11 and set the base image openjdk:11 to build the example from
- Use another client like restassured
- Use awaits to retry several times

Nothing of above worked.

An alternative solution could be not use port fordwarding but LoadBalancer which works fine in Kind when running on the CI environment.

**Comment by Sgitario** [comment]
@iocanel this PR https://github.com/dekorateio/dekorate/pull/819 should fix this issue, right? Asking whether we should close this now.
